name             'myfacts'
maintainer       'Pradeep Joshi'
maintainer_email 'pcjoshi9@gmail.com'
license          'All rights reserved'
description      'Installs/Configures myfacts'
long_description 'Installs/Configures myfacts'
version          '0.27.0'
depends 'apt'
